[workspace]

members = ["crates/rglauncher-core", "crates/rglauncher-gtk", "vendor/mdict"]

resolver = "2"

[workspace.dependencies]
chin-tools = { git = "https://github.com/aeghn/chin-tools" }


[profile.release]
lto = true
opt-level = 3
