[workspace]

members = ["crates/rglauncher-core", "crates/rglauncher-gtk", "vendor/mdict"]

resolver = "2"

[workspace.dependencies]
chin-tools = { path = "/home/chin/Projects/chin-tools" }


[profile.release]
lto = true
opt-level = 3
