[workspace]

members = ["crates/rglauncher-core", "crates/rglauncher-gtk", "vendor/mdict"]

resolver = "2"

[workspace.dependencies]
async-broadcast = "0.7.0"


[profile.release]
lto = true
opt-level = 3
